2024-11-26 09:46:03,309 DEBUG    root            Loaded Command Group: ['gcloud', 'iam']
2024-11-26 09:46:03,333 DEBUG    root            Loaded Command Group: ['gcloud', 'iam', 'roles']
2024-11-26 09:46:03,369 DEBUG    root            Loaded Command Group: ['gcloud', 'iam', 'roles', 'create']
2024-11-26 09:46:03,373 DEBUG    root            Running [gcloud.iam.roles.create] with arguments: [--permissions: "storage.objects.get,storage.objects.create,pubsub.topics.publish,cloudfunctions.functions.invoke", --project: "inspired-photon-441609-k7", --title: "Custom role for needed services", ROLE_ID: "main_custom_role"]
2024-11-26 09:46:03,388 DEBUG    root            (gcloud.iam.roles.create) Your current active account [trigger-account@inspired-photon-441609-k7.iam.gserviceaccount.com] does not have any valid credentials
Please run:

  $ gcloud auth login

to obtain new credentials.

For service account, please activate it first:

  $ gcloud auth activate-service-account ACCOUNT
Traceback (most recent call last):
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/calliope/backend.py", line 843, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/surface/iam/roles/create.py", line 76, in Run
    client, messages = util.GetClientAndMessages()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/api_lib/iam/util.py", line 28, in GetClientAndMessages
    client = apis.GetClientInstance('iam', 'v1')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/api_lib/util/apis.py", line 270, in GetClientInstance
    return apis_internal._GetClientInstance(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/api_lib/util/apis_internal.py", line 169, in _GetClientInstance
    http_client = transports.GetApitoolsTransport(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/core/credentials/transports.py", line 80, in GetApitoolsTransport
    session = requests.GetSession(
              ^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/core/credentials/requests.py", line 82, in GetSession
    session = request_wrapper.WrapQuota(session, enable_resource_quota,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/core/credentials/requests.py", line 127, in WrapQuota
    quota_project = self.QuotaProject(enable_resource_quota,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/core/credentials/transport.py", line 54, in QuotaProject
    creds = store.LoadIfEnabled(allow_account_impersonation, use_google_auth)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/core/credentials/store.py", line 636, in LoadIfEnabled
    return Load(
           ^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/core/credentials/store.py", line 876, in Load
    cred = _Load(
           ^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/core/credentials/store.py", line 1073, in _Load
    raise NoCredentialsForAccountException(account)
googlecloudsdk.core.credentials.store.NoCredentialsForAccountException: Your current active account [trigger-account@inspired-photon-441609-k7.iam.gserviceaccount.com] does not have any valid credentials
Please run:

  $ gcloud auth login

to obtain new credentials.

For service account, please activate it first:

  $ gcloud auth activate-service-account ACCOUNT
2024-11-26 09:46:03,398 ERROR    root            (gcloud.iam.roles.create) Your current active account [trigger-account@inspired-photon-441609-k7.iam.gserviceaccount.com] does not have any valid credentials
Please run:

  $ gcloud auth login

to obtain new credentials.

For service account, please activate it first:

  $ gcloud auth activate-service-account ACCOUNT
