2024-11-26 15:22:54,761 DEBUG    root            Loaded Command Group: ['gcloud', 'storage']
2024-11-26 15:22:54,763 DEBUG    root            Loaded Command Group: ['gcloud', 'storage', 'buckets']
2024-11-26 15:22:55,013 DEBUG    root            Loaded Command Group: ['gcloud', 'storage', 'buckets', 'create']
2024-11-26 15:22:55,020 DEBUG    root            Running [gcloud.storage.buckets.create] with arguments: [--location: "us-central1", URL:1: "['gs://main-bucket-5505']"]
2024-11-26 15:22:55,020 INFO     ___FILE_ONLY___ Creating gs://main-bucket-5505/...

2024-11-26 15:22:55,156 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): storage.googleapis.com:443
2024-11-26 15:22:55,326 DEBUG    urllib3.connectionpool https://storage.googleapis.com:443 "POST /storage/v1/b?alt=json&enableObjectRetention=False&project=inspired-photon-441609-k7&projection=noAcl HTTP/1.1" 403 608
2024-11-26 15:22:55,330 DEBUG    root            (gcloud.storage.buckets.create) HTTPError 403: trigger-account@inspired-photon-441609-k7.iam.gserviceaccount.com does not have storage.buckets.create access to the Google Cloud project. Permission 'storage.buckets.create' denied on resource (or it may not exist). This command is authenticated as trigger-account@inspired-photon-441609-k7.iam.gserviceaccount.com which is the active account specified by the [core/account] property.
Traceback (most recent call last):
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/api_lib/storage/errors.py", line 316, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/api_lib/storage/gcs_json/client.py", line 523, in create_bucket
    created_bucket_metadata = self.client.buckets.Insert(request)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/generated_clients/apis/storage/v1/storage_v1_client.py", line 539, in Insert
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://storage.googleapis.com/storage/v1/b?alt=json&enableObjectRetention=False&project=inspired-photon-441609-k7&projection=noAcl>: response: <{'content-type': 'application/json; charset=UTF-8', 'date': 'Tue, 26 Nov 2024 15:22:55 GMT', 'vary': 'Origin, X-Origin', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'pragma': 'no-cache', 'x-guploader-uploadid': 'AFiumC7jl7m3IBjpM5PhDmdbbOZv70kZoH9h2ghucxHAHvOwg_m47reYNIVfZAVVxPKnhV2PTps', 'content-length': '608', 'server': 'UploadServer', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "trigger-account@inspired-photon-441609-k7.iam.gserviceaccount.com does not have storage.buckets.create access to the Google Cloud project. Permission 'storage.buckets.create' denied on resource (or it may not exist).",
    "errors": [
      {
        "message": "trigger-account@inspired-photon-441609-k7.iam.gserviceaccount.com does not have storage.buckets.create access to the Google Cloud project. Permission 'storage.buckets.create' denied on resource (or it may not exist).",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
}
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/calliope/backend.py", line 843, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/surface/storage/buckets/create.py", line 176, in Run
    ).execute()
      ^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/command_lib/storage/tasks/buckets/create_bucket_task.py", line 48, in execute
    api_factory.get_api(provider).create_bucket(
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/api_lib/storage/errors.py", line 320, in wrapper
    core_exceptions.reraise(
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/core/exceptions.py", line 149, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/snap/google-cloud-cli/289/lib/third_party/six/__init__.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/api_lib/storage/errors.py", line 316, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/api_lib/storage/gcs_json/client.py", line 523, in create_bucket
    created_bucket_metadata = self.client.buckets.Insert(request)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/generated_clients/apis/storage/v1/storage_v1_client.py", line 539, in Insert
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
googlecloudsdk.api_lib.storage.errors.GcsApiError: HTTPError 403: trigger-account@inspired-photon-441609-k7.iam.gserviceaccount.com does not have storage.buckets.create access to the Google Cloud project. Permission 'storage.buckets.create' denied on resource (or it may not exist). This command is authenticated as trigger-account@inspired-photon-441609-k7.iam.gserviceaccount.com which is the active account specified by the [core/account] property.
2024-11-26 15:22:55,335 ERROR    root            (gcloud.storage.buckets.create) HTTPError 403: trigger-account@inspired-photon-441609-k7.iam.gserviceaccount.com does not have storage.buckets.create access to the Google Cloud project. Permission 'storage.buckets.create' denied on resource (or it may not exist). This command is authenticated as trigger-account@inspired-photon-441609-k7.iam.gserviceaccount.com which is the active account specified by the [core/account] property.
