2024-11-26 17:39:43,157 DEBUG    root            Loaded Command Group: ['gcloud', 'pubsub']
2024-11-26 17:39:43,158 DEBUG    root            Loaded Command Group: ['gcloud', 'pubsub', 'topics']
2024-11-26 17:39:43,196 DEBUG    root            Loaded Command Group: ['gcloud', 'pubsub', 'topics', 'create']
2024-11-26 17:39:43,274 DEBUG    root            Running [gcloud.pubsub.topics.create] with arguments: [TOPIC:1: "['gcs-trigger-topic']"]
2024-11-26 17:39:43,274 DEBUG    root            Chosen display Format:none
2024-11-26 17:39:43,274 INFO     root            Display format: "none"
2024-11-26 17:39:43,582 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): pubsub.googleapis.com:443
2024-11-26 17:39:47,409 DEBUG    urllib3.connectionpool https://pubsub.googleapis.com:443 "PUT /v1/projects/inspired-photon-441609-k7/topics/gcs-trigger-topic?alt=json HTTP/1.1" 409 None
2024-11-26 17:39:47,413 ERROR    root            Failed to create topic [projects/inspired-photon-441609-k7/topics/gcs-trigger-topic]: Resource already exists in the project (resource=gcs-trigger-topic).
2024-11-26 17:39:47,414 DEBUG    root            (gcloud.pubsub.topics.create) Failed to create the following: [gcs-trigger-topic].
Traceback (most recent call last):
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/calliope/backend.py", line 845, in Run
    display_info=self.ai.display_info).Display()
                                       ^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/calliope/display.py", line 487, in Display
    self._printer.Print(self._resources)
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/core/resource/resource_printer_base.py", line 301, in Print
    for resource in resources:
  File "/snap/google-cloud-cli/289/lib/surface/pubsub/topics/create.py", line 256, in _Run
    raise util.RequestsFailedError(failed, 'create')
googlecloudsdk.command_lib.pubsub.util.RequestsFailedError: Failed to create the following: [gcs-trigger-topic].
2024-11-26 17:39:47,453 ERROR    root            (gcloud.pubsub.topics.create) Failed to create the following: [gcs-trigger-topic].
